name: E2E Tests Docs

on: [push]

defaults:
  run:
    working-directory: ./docs

jobs:
  cypress-run:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn install
        working-directory: ./docs

      - name: Set the right environment
        run: export OBJECTIV_ENVIRONMENT='development'

      - name: Run Cypress tests
        uses: cypress-io/github-action@v4
        working-directory: ./docs
        with:
          browser: chrome
          install: false
          start: yarn start
          wait-on: 'http://localhost:3000/docs'
          project: ./docs/
