name: E2E Tests Docs

on: [push]

defaults:
  run:
    working-directory: ./docs

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install website dotenv
        run: yarn add dotenv

      - name: Install dependencies
        working-directory: docs
        run: yarn install

      - name: Run Cypress tests
        uses: cypress-io/github-action@v4
        with:
          working-directory: docs
          install: false
          env: OBJECTIV_ENVIRONMENT=development
          start: yarn start
          wait-on: 'http://localhost:3000/docs'
          wait-on-timeout: 120
#          project: ./docs/
