name: E2E Tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn install

      - name: Run Cypress tests
        uses: cypress-io/github-action@v4
        with:
          browser: chrome
          install: false
          start: yarn start
          wait-on: 'http://localhost:3000'

  cypress-run:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn install

      - name: Run Cypress tests
        uses: cypress-io/github-action@v4
        with:
          browser: chrome
          install: false
          start: yarn start
          wait-on: 'http://localhost:3000'
          project: ./docs/
